import Head from "next/head";
import { BiCheck, BiUserPlus, BiX } from "react-icons/bi";
import Table from "../components/Table";
import Form from "../components/Form";
import { useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import { toggleChangAction, deleteAction } from "../redux/reducer";
import { deleteUser, getUsers } from "../lib/helper";
import { useQueryClient } from "react-query";

export default function Home() {
  const visible = useSelector((state) => state.app.client.toggleForm)
  const deleteId = useSelector((state) => state.app.client.deleteId)
  const queryClient = useQueryClient()
  const dispatch = useDispatch()

  const handler = () => {
    dispatch(toggleChangAction())
  };

  const deletehandler = async () => {
    console.log(deleteId)
    if (deleteId) {
      await deleteUser(deleteId)
      await queryClient.prefetchQuery('users', getUsers)
      await dispatch(deleteAction(null))
    }
  }

  const canclehandler = async () => {
    await dispatch(deleteAction(null))
  }

  return (
    <>
      <Head>
        <title>CRUD NEXT.JS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-5">
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Employee Management
        </h1>
        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button onClick={handler} className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800">
              Add Employee <BiUserPlus size={23}></BiUserPlus>
            </button>
          </div>
          {deleteId ? DeleteComponent({ deletehandler, canclehandler }) : <></>}
        </div>

        {/* form */}
        {visible ? <Form></Form> : <></>}

        {/* table */}
        <div className="container mx-auto">
          <Table></Table>
        </div>
      </main>
    </>
  );
}


function DeleteComponent({ deletehandler, canclehandler }) {
  return (
    <div className="flex gap-5">
      <p>Are you sure?</p>
      <button onClick={deletehandler} className="flex bg-red-500 text-white px-4 py-2 border rounded-md hover:border-red-500 hover:text-gray-50">
        Yes <span className="px-1"><BiX color="rgb(255 255 255)" size={25} /></span></button>
      <button className="flex bg-green-500 text-white px-4 py-2 border rounded-md  hover:border-green-500 hover:text-gray-50">
        No <span onClick={canclehandler} className="px-1"><BiCheck color="rgb(255 255 255)" size={25} /></span></button>
    </div>
  )
}
